import {test} from 'node:test';
import assert from 'node:assert/strict';
import {evaluate,validateDuration,validateFile} from '../src/analysis.js';
test('upload boundaries',()=>{assert.throws(()=>validateFile({name:'x.html',size:4}));assert.throws(()=>validateFile({name:'x.mp4',size:101*1024*1024}));assert.throws(()=>validateDuration(Infinity));assert.throws(()=>validateDuration(9));validateDuration(10);validateDuration(30);validateFile({name:'x.MOV',size:4});});
const frames=(foot=28)=>Array.from({length:60},(_,i)=>{const pose=Array.from({length:33},()=>({x:.5,y:.5,visibility:.99}));pose[0].y=.1;pose[11]={x:.42,y:.3,visibility:.99};pose[12]={x:.58,y:.3,visibility:.99};pose[23]={x:.45,y:.55,visibility:.99};pose[24]={x:.55,y:.55,visibility:.99};pose[27]={x:.43,y:.9,visibility:.99};pose[28]={x:.57,y:.9,visibility:.99};pose[foot].x+=i>=25&&i<=30?(i-25)*.035:i>30?.175:0;return {time:i/6,pose,people:1,light:120,sharpness:10};});
const options={foot:'right',direction:'side',goal:'balance',aspect:16/9};
test('both feet have bounded evidence linked observations',()=>{for(const foot of ['right','left']){const result=evaluate(frames(foot==='right'?28:27),{...options,foot},1);assert.equal(result.issues.length,0);assert.equal(result.phases.length,4);assert.ok(result.advice.length>0&&result.advice.length<=3);for(const a of result.advice)assert.ok(result.phases.some(p=>p.time===a.time));assert.ok(Number.isFinite(result.metrics.tilt));}});
test('occluded feet, dark video and multiple people suppress advice',()=>{for(const alter of [f=>{f.pose[28].visibility=.1;},f=>{f.light=10;},f=>{f.people=2;},f=>{f.sharpness=0;}]){const data=frames();data.forEach(alter);const result=evaluate(data,options,1);assert.ok(result.issues.length);assert.equal(result.advice.length,0);assert.equal(result.metrics,null);}});
test('frontal footage suppresses directional pelvis advice',()=>{const result=evaluate(frames(),{...options,direction:'front'},1);assert.ok(!result.advice.some(a=>a.title.includes('骨盤')));});
