export const dashboard = `
<header><a class="brand" href="/">◉ PASS NOTE</a><span class="badge">パス動作 · 検証版</span><details class="help"><summary>撮影ガイド</summary><div><strong>横から、全身とボールを固定撮影</strong><p>明るい場所で、選手1人のパスを撮影。頭と足先に余白を入れてください。説明が含まれる動画でも、蹴る前後の連続した場面を解析します。</p><p>重心・荷重・接触は測定できません。助言は指導者による検証前です。</p><p>ファイルは端末内で処理。YouTubeの指定区間はこのPCで一時取得し、転送後に削除。動画と結果はページを閉じるまで保持します。</p></div></details></header>
<main><div class="dashboard-title"><div><h1>パスの分析</h1><p>動画を選んで、次の一本で試すことを見つける。</p></div><span class="local-note">● 動画は非公開</span></div>
<div class="dashboard"><section class="panel workspace"><h2>動画を選ぶ</h2><form id="form"><div class="source-tabs" role="group" aria-label="動画の入力方法"><button id="source-youtube" type="button" aria-pressed="true">YouTubeリンク</button><button id="source-file" type="button" aria-pressed="false">動画ファイル</button></div>
<div id="youtube-input"><label for="youtube-url">動画リンク</label><input id="youtube-url" type="url" placeholder="YouTubeのリンクを貼り付け" autocomplete="off"><div class="fields clip-fields"><label>開始位置（秒）<input id="youtube-start" type="number" min="0" max="21600" step="1" value="0"></label><label>長さ（秒）<select id="youtube-duration"><option value="10">10秒</option><option value="20">20秒</option><option value="30">30秒</option></select></label></div><p class="muted">公開・録画済みの動画に対応。パス1回を含む区間を指定。</p></div>
<label class="upload" for="file" hidden><strong id="filename">動画ファイルを選ぶ</strong><span>10〜30秒 / 100MBまで</span><input id="file" type="file" accept="video/mp4,video/quicktime,video/webm,.mp4,.mov,.webm"></label>
<div class="foot-field"><label for="foot">蹴り足</label><select id="foot"><option value="right">右足</option><option value="left">左足</option></select></div>
<details class="settings"><summary>撮影方向・練習目的</summary><div class="fields"><label>撮影方向<select id="direction"><option value="side">横から</option><option value="diagonal">斜めから</option><option value="front">正面から</option></select></label><label>練習の目的<select id="goal"><option value="balance">安定して蹴りたい</option><option value="accuracy">狙った場所へ送りたい</option><option value="review">動きを振り返りたい</option></select></label></div></details>
<p class="capture-note">蹴る前後に、選手の胴体・両足・ボールが映る区間を選んでください。接触面の種類や飛距離は測定しません。</p><button id="analyze" class="primary" disabled>解析する <span>→</span></button></form><div id="status" role="status" aria-live="polite">リンクを貼るか、動画ファイルを選択してください。</div><progress id="progress" max="1" value="0" hidden></progress><button id="cancel" class="secondary" type="button" hidden>中止して削除</button></section>
<section class="panel review"><div class="section-head"><h2>動画と分析結果</h2><span class="tag">最大3つの改善点</span></div><div id="video-empty" class="empty-video"><span>▷</span><strong>ここでフォームを振り返る</strong><p>動画を選び「解析する」を押してください。<br>根拠の場面と練習方法を表示します。</p></div><div id="preview" hidden><div class="video-stage"><video id="video" controls playsinline preload="auto"></video><canvas id="overlay"></canvas></div><div class="preview-tools"><label class="check"><input id="show-pose" type="checkbox" checked> 関節・ボールを表示</label><button id="delete" class="text-button" type="button">動画と結果を削除</button></div></div><div id="results" class="results" hidden></div><div id="result-empty" class="result-empty"><span>観察 → 根拠の場面 → 次に試す練習</span><p>点数ではなく、動画で確認できる動きを示します。</p></div></section></div></main>`;
